version: '2.3'

services:
  conductor-server:
    environment:
      - CONFIG_PROP=config-oracle-es7.properties
    image: conductor:server
    container_name: conductor-server
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
      args:
        YARN_OPTS: --network-timeout 10000000
        #YARN_OPTS: ${YARN_OPTS}
    networks:
      - internal
    ports:
      - 8080:8080
      - 5000:5000
    healthcheck:
      test: [ "CMD", "curl","-I" ,"-XGET", "http://localhost:8080/health" ]
      interval: 60s
      timeout: 30s
      retries: 12
    links:
      - conductor-oracle:oracle
      - conductor-elasticsearch:es
    depends_on:
      conductor-oracle:
        condition: service_healthy
      conductor-elasticsearch:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    volumes:
      - ./server/config/config-oracle-es7.properties:/app/config/config-oracle-es7.properties:ro

  conductor-oracle:
    # image: conductorboot/oracle:19.3.0-ee-slim-test
    image: gvenzl/oracle-xe:21.3.0-slim
    environment:
      - ORACLE_PASSWORD=conductor
      - ORACLE_DATABASE=conductor
      - APP_USER=conductor
      - APP_USER_PASSWORD=conductor
    volumes:
      - oracledata-conductor:/opt/oracle/oradata
    networks:
      - internal
    ports:
      - 1521:1521
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/1521'
      interval: 60s
      timeout: 30s
      start_period: 180s
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  conductor-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.11
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - esdata-conductor:/usr/share/elasticsearch/data
    networks:
      - internal
    ports:
      - 9201:9200
    healthcheck:
      test: curl http://localhost:9200/_cluster/health -o /dev/null
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

volumes:
  oracledata-conductor:
    driver: local
  esdata-conductor:
    driver: local
networks:
  internal: