site_name: Conductor
theme_dir: docs/theme
repo_url: https://github.com/Netflix/conductor
strict: True

pages:
- 'Introduction' : index.md
- 'Getting Started': intro/index.md
- 'Basic Concepts': intro/concepts.md
- 'Metadata Definitions': metadata/index.md
- 'System Tasks': metadata/systask.md
- 'Kitchensink Example': metadata/kitchensink.md
- 'Conductor Server': server/index.md
- 'Extending Conductor': extend/index.md
- 'Workflow Management': runtime/index.md
- 'Workflow Metrics':
   - 'Server Metrics': metrics/index.md
   - 'Worker Metrics': metrics/client.md
- License: 'license.md'
theme: readthedocs
extra_css:
    - css/custom.css
markdown_extensions:
- admonition
- toc:
    permalink: True    
