site_name: Conductor
repo_url: https://github.com/Netflix/conductor
edit_uri: edit/dev/docs/docs/
strict: true

nav:
    - Introduction: index.md
    - Architecture: architecture.md
    - Getting Started:
        - Basic Concepts: gettingstarted/basicconcepts.md
        - Using the Client: gettingstarted/client.md
        - Start a Workflow: gettingstarted/startworkflow.md
    - Configuration:
        - Task Definition: configuration/taskdef.md
        - Workflow Definition: configuration/workflowdef.md
        - System Tasks: configuration/systask.md
        - Event Handlers: configuration/eventhandlers.md
        - Task Domains: configuration/taskdomains.md
        - Isolation Groups: configuration/isolationgroups.md
    - Conductor Server: server.md
    - API Specification: apispec.md
    - Conductor Metrics:
        - Server Metrics: metrics/server.md
        - Client Metrics: metrics/client.md
    - Extending Conductor: extend.md
    - Task Lifecycle: tasklifecycle.md
    - External Payload Storage: externalpayloadstorage.md
    - Developer Labs:
        - Beginner: labs/beginner.md
        - Events and Event Handlers: labs/eventhandlers.md
        - Kitchensink: labs/kitchensink.md
    - Best Practices: bestpractices.md
    - FAQ: faq.md
    - Technical Details: technicaldetails.md
    - License: license.md
theme: readthedocs
extra_css:
    - css/custom.css
markdown_extensions:
- toc:
    permalink: true
- admonition
- codehilite
